baseURL       = 'https://www.fcgreviews.com'
languageCode  = 'en-us'
title         = 'Film Critics Guild Reviews'
theme         = 'guild'
summaryLength = 30

[pagination]
pagerSize = 6

[module]
[module.hugoVersion]
extended = true
min      = "0.145.0"

[taxonomies]
critic  = 'critics'
mreview = 'mreviews'

[outputs]
taxonomy = ['json', 'html']
term     = ['json', 'html']

[security.http]
mediaTypes = ['^audio/mpeg$']
