baseURL       = 'https://www.fcgreviews.com'
locale        = 'en_US.UTF-8'
title         = 'Film Critics Guild Reviews'
theme         = 'guild'
summaryLength = 30

[params]
    maxCastLength = 10
    algoliaSearchEndpoint = 'https://9lk62c0eb5.execute-api.ap-south-1.amazonaws.com/Prod/search'
    apiKey = "qkIQ6276FyaRzBlhxM3kN8BGd22TWNyN9LNK7qSC"
    turnstileSiteKey = "0x4AAAAAACtG4_fmCXPDKJ4q"

[pagination]
pagerSize = 6

[module]
[module.hugoVersion]
extended = true
min      = "0.145.0"

[taxonomies]
critic  = 'critics'
mreview = 'mreviews'

[outputFormats]
    [outputFormats.meta]
        mediaType = "application/json"
        path = "tmdb-meta"
        isHTML = false

[outputs]
taxonomy = ['html', 'json']
term     = ['html', 'json', 'meta']

[security.http]
mediaTypes = ['^audio/mpeg$']

[mediaTypes.'audio/mpeg']
suffixes = ['mp3']