baseURL       = 'https://www.fcgreviews.com'
languageCode  = 'en-us'
title         = 'Film Critics Guild Reviews'
theme         = 'guild'
summaryLength = 30

[params]
    algoliaSearchEndpoint = 'https://z0njtycwm6.execute-api.ap-south-1.amazonaws.com/prod/search'
    apiKey = "qkIQ6276FyaRzBlhxM3kN8BGd22TWNyN9LNK7qSC"

[pagination]
pagerSize = 6

[module]
[module.hugoVersion]
extended = true
min      = "0.145.0"

[taxonomies]
critic  = 'critics'
mreview = 'mreviews'

[outputs]
taxonomy = ['json', 'html']
term     = ['json', 'html']

[security.http]
mediaTypes = ['^audio/mpeg$']

[mediaTypes.'audio/mpeg']
suffixes = ['mp3']